# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170813_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(choices=[('academic', 'Academic'), ('commercial', 'Commercial'), ('public-sector', 'Public Sector'), ('healthcare', 'Healthcare'), ('non-profit', 'Non-profit'), ('other', 'Other')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
