# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170813_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
