# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20170917_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reason',
            field=models.CharField(choices=[('DWL', 'Download Issue'), ('INS', 'Installation/Licensing Issue'), ('SWI', 'Software Issue'), ('OTH', 'Other')], default='OTH', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PCR', 'Pending Customer Response'), ('PER', 'Pending easySPSS Response'), ('CLS', 'Closed')], default='NEW', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
