# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170912_2246'),
        ('tickets', '0010_auto_20170926_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='product',
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='products.Purchase'),
            preserve_default=False,
        ),
    ]
