# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('osystem', models.CharField(default='', max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('license_type', models.CharField(choices=[('1 year', '1 Year'), ('2 years', '2 Years'), ('perpetual', 'Perpetual')], default='1 year', max_length=50)),
            ],
        ),
    ]
